neo4j:
  edition: community
  name: neo4j
  password: supersecret
  resources:
    cpu: "2000m"
    memory: "4Gi"

services:
  neo4j:
    type: ClusterIP

volumes:
  data:
    mode: defaultStorageClass
