apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: spark
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2024-07-16T23-46-41Z
        command: ["minio", "server", "/data", "--console-address", ":9001"]
        ports:
        - containerPort: 9000
          name: minio
        - containerPort: 9001
          name: minio-console
        env:
          - name: MINIO_ROOT_USER
            value: minio-access-key
          - name: MINIO_ROOT_PASSWORD
            value: minio-secret-key
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: spark
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    name: minio
    targetPort: minio
    protocol: TCP
  - port: 9001
    name: minio-console
    targetPort: minio-console
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: spark
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
