deploy:
  #!/bin/bash
  set -e
  k3d cluster ls | grep spark || k3d cluster create spark --registry-create spark-registry:0.0.0.0:5000 -p "8443:443@loadbalancer" -p "8080:80@loadbalancer"
  helm repo add spark-operator https://kubeflow.github.io/spark-operator
  helm repo update
  helm upgrade --install spark-operator spark-operator/spark-operator -n spark-operator --create-namespace --set webhook.enable=true
  helm upgrade --install mongodb oci://registry-1.docker.io/bitnamicharts/mongodb -f deploy/mongodb.yaml -n spark --create-namespace
  kubectl create namespace kafka || true
  kubectl apply -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka
  kubectl apply -f deploy/kafka.yaml
  kubectl apply -f deploy/minio.yaml
  kubectl apply -f deploy/neo4j.yaml
  # init minio
  kubectl wait deployment/minio --for=jsonpath='{.status.readyReplicas}'=1 --timeout=300s -n spark
  MINIO_POD=$(kubectl get pods -n spark -l app=minio -o jsonpath='{.items[0].metadata.name}')
  kubectl exec -it ${MINIO_POD} -n spark -- mc alias set minio http://localhost:9000 minio-access-key minio-secret-key
  kubectl exec -it ${MINIO_POD} -n spark -- mc mb minio/data -p
  kubectl exec -it ${MINIO_POD} -n spark -- mc mb minio/deployments -p
  kubectl exec -it ${MINIO_POD} -n spark -- mc anonymous set public minio/deployments
  # init kafka
  kubectl wait pods/my-cluster-dual-role-0 --for=condition=Ready --timeout=300s -n kafka
  kubectl exec -it my-cluster-dual-role-0 -n kafka -- ./bin/kafka-topics.sh --create --topic movies --bootstrap-server localhost:9092 --partitions 3 --replication-factor 1


delete:
  k3d cluster delete spark

run MAIN_CLASS:
  #!/bin/bash
  set -e
  sbt compile assembly
  MAIN_CLASS={{MAIN_CLASS}} envsubst < app.yaml > app-{{MAIN_CLASS}}.yaml
  MINIO_POD=$(kubectl get pods -n spark -l app=minio -o jsonpath='{.items[0].metadata.name}')
  docker run --rm \
  --network host \
  -v $(pwd)/target/scala-2.12/spark-getting-started-assembly-0.0.1.jar:/tmp/app.jar \
  --entrypoint /bin/sh minio/mc -c "
    mc alias set myminio http://localhost:9000 minio-access-key minio-secret-key &&
    mc cp /tmp/app.jar myminio/deployments/
  "
  kubectl delete -f app-{{MAIN_CLASS}}.yaml || true
  kubectl apply -f app-{{MAIN_CLASS}}.yaml

build-docker:
  #!/bin/bash
  set -e
  sbt compile assembly
  docker build -t spark-getting-started:latest -f Dockerfile .
  k3d image import spark-getting-started:latest -c spark

restart MAIN_CLASS: 
  kubectl delete -f app-{{MAIN_CLASS}}.yaml || true
  kubectl apply -f app-{{MAIN_CLASS}}.yaml

pf:
  kubectl port-forward svc/minio -n spark 9000:9000 9001:9001
